site_url: https://nonskating.club
backend:
  name: github
  repo: davidmreed/nonskating.club
  open_authoring: true
  branch: main
  auth_scope: repo
  base_url: https://fragrant-river-8742.david-a8d.workers.dev/
publish_mode: editorial_workflow
media_folder: static
media_library:
  name: ""
  display_in_navigation: false
collections:
  - name: 'guides'
    label: 'Guides'
    folder: 'content/guides'
    create: true
    delete: false
    slug: '{{slug}}'
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'guide.html' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', format: 'yyyy-MM-dd', date_format: 'yyyy-MM-dd', time_format: false, picker_utc: true }
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    editor:
      preview: false
